exclude = [
    "websi",
    "vroomo",
    "venv",
    "staticfiles",
    "media",
    "locale",
    "__pycache__",
]

[lint]
ignore = ["EXE001"]

[lint.per-file-ignores]
"fleet/migrations/*.py" = ["RUF012"]
"fleet/models.py" = ["RUF012"]
"fleet/forms.py" = ["RUF012"]
"fleet/admin.py" = ["RUF012"]
