# Generated by Django 5.1.15 on 2026-07-19 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('last_name', models.CharField(max_length=100, verbose_name='اللقب')),
                ('cin', models.CharField(max_length=20, unique=True, verbose_name='رقم البطاقة الوطنية')),
                ('phone', models.CharField(max_length=20, verbose_name='الهاتف')),
                ('license_number', models.CharField(max_length=30, verbose_name='رقم الرخصة')),
                ('license_expiry', models.DateField(verbose_name='انتهاء الرخصة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'سائق',
                'verbose_name_plural': 'السائقون',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='رقم اللوحة')),
                ('make', models.CharField(max_length=50, verbose_name='الماركة')),
                ('model', models.CharField(max_length=50, verbose_name='الموديل')),
                ('year', models.IntegerField(verbose_name='السنة')),
                ('status', models.CharField(choices=[('available', 'متاحة'), ('rented', 'مؤجرة'), ('maintenance', 'صيانة'), ('out_of_service', 'خارج الخدمة')], default='available', max_length=20, verbose_name='الحالة')),
                ('current_km', models.IntegerField(default=0, verbose_name='الكيلومترات الحالية')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر اليومي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مركبة',
                'verbose_name_plural': 'المركبات',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('km_at_service', models.IntegerField(verbose_name='الكيلومترات عند الصيانة')),
                ('type', models.CharField(max_length=100, verbose_name='النوع')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='التكلفة')),
                ('next_service_km', models.IntegerField(blank=True, null=True, verbose_name='الصيانة القادمة عند (كلم)')),
                ('next_service_date', models.DateField(blank=True, null=True, verbose_name='الصيانة القادمة (تاريخ)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='fleet.vehicle', verbose_name='المركبة')),
            ],
            options={
                'verbose_name': 'صيانة',
                'verbose_name_plural': 'الصيانة',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='هاتف العميل')),
                ('pickup_date', models.DateTimeField(verbose_name='تاريخ الاستلام')),
                ('expected_return', models.DateTimeField(verbose_name='تاريخ الرجوع المتوقع')),
                ('actual_return', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرجوع الفعلي')),
                ('pickup_km', models.IntegerField(default=0, verbose_name='كيلومترات الاستلام')),
                ('return_km', models.IntegerField(blank=True, null=True, verbose_name='كيلومترات الرجوع')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الضمان')),
                ('status', models.CharField(choices=[('confirmed', 'مؤكد'), ('rented', 'مؤجرة'), ('returned', 'مُرجعة'), ('late', 'متأخرة'), ('cancelled', 'ملغاة')], default='confirmed', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='fleet.driver', verbose_name='السائق')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='fleet.vehicle', verbose_name='المركبة')),
            ],
            options={
                'verbose_name': 'حجز',
                'verbose_name_plural': 'الحجوزات',
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('carte_grise', 'البطاقة الرمادية'), ('insurance', 'التأمين'), ('visite_technique', 'الفحص التقني'), ('vignette', 'الفينييت')], max_length=30, verbose_name='نوع الوثيقة')),
                ('doc_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الوثيقة')),
                ('expiry_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('file', models.FileField(blank=True, upload_to='documents/', verbose_name='الملف')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fleet.vehicle', verbose_name='المركبة')),
            ],
            options={
                'verbose_name': 'وثيقة مركبة',
                'verbose_name_plural': 'وثائق المركبات',
            },
        ),
    ]
