# Generated by Django 6.0.7 on 2026-07-19 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_date', models.DateTimeField(verbose_name='تاريخ المخالفة')),
                ('violation_location', models.CharField(blank=True, max_length=300, verbose_name='المكان')),
                ('violation_type', models.CharField(choices=[('speeding', 'تجاوز السرعة'), ('red_light', 'عدم احترام إشارة'), ('seatbelt', 'عدم وضع حزام'), ('phone', 'استخدام الهاتف'), ('parking', 'وقوف ممنوع'), ('other', 'أخرى')], default='other', max_length=30, verbose_name='نوع المخالفة')),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ الغرامة')),
                ('majoration_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الزيادة')),
                ('notification_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التبليغ')),
                ('payment_deadline', models.DateField(blank=True, null=True, verbose_name='آخر أجل للدفع')),
                ('status', models.CharField(choices=[('new', 'جديدة'), ('driver_designated', 'تم تحديد السائق'), ('paid', 'مدفوعة'), ('disputed', 'متنازع عليها'), ('overdue', 'تجاوزت الأجل')], default='new', max_length=20, verbose_name='الحالة')),
                ('paid_by', models.CharField(blank=True, max_length=20, verbose_name='دفعها')),
                ('points_deducted', models.IntegerField(default=0, verbose_name='النقاط المخصومة')),
                ('pv_number', models.CharField(blank=True, max_length=50, verbose_name='رقم المحضر')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='fleet.booking', verbose_name='الحجز')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='fleet.driver', verbose_name='السائق')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='violations', to='fleet.vehicle', verbose_name='المركبة')),
            ],
            options={
                'verbose_name': 'مخالفة',
                'verbose_name_plural': 'المخالفات',
            },
        ),
    ]
