# Generated by Django 6.0.7 on 2026-07-29 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import fleet.validators


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_violation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledocument',
            name='file',
            field=models.FileField(blank=True, upload_to=fleet.validators.DocumentUploadTo(), validators=[fleet.validators.validate_file_extension, fleet.validators.validate_file_size, fleet.validators.validate_mime_type], verbose_name='الملف'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='اسم المستخدم')),
                ('ip_address', models.GenericIPAddressField(null=True, verbose_name='عنوان IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='المتصفح')),
                ('action', models.CharField(choices=[('LOGIN', 'تسجيل دخول'), ('LOGOUT', 'تسجيل خروج'), ('LOGIN_FAILED', 'فشل تسجيل دخول'), ('CREATE', 'إضافة'), ('UPDATE', 'تعديل'), ('DELETE', 'حذف'), ('CHANGE_STATUS', 'تغيير حالة'), ('PICKUP', 'استلام'), ('RETURN', 'إرجاع')], max_length=20, verbose_name='الإجراء')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='نوع الكائن')),
                ('object_id', models.CharField(blank=True, max_length=50, verbose_name='معرف الكائن')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='تمثيل الكائن')),
                ('change_summary', models.CharField(blank=True, max_length=500, verbose_name='ملخص التغيير')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل التدقيق',
                'verbose_name_plural': 'سجلات التدقيق',
                'ordering': ['-created_at'],
            },
        ),
    ]
