# Generated by Django 6.0.7 on 2026-07-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_vehicledocument_file_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, verbose_name='مفتاح الجلسة'),
        ),
    ]
