# Generated by Django 6.0.7 on 2026-07-31 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import fleet.validators


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_make_company_non_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Audit log', 'verbose_name_plural': 'Audit logs'},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Driver', 'verbose_name_plural': 'Drivers'},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'verbose_name': 'Maintenance', 'verbose_name_plural': 'Maintenance records'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User profile', 'verbose_name_plural': 'User profiles'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.AlterModelOptions(
            name='vehicledocument',
            options={'verbose_name': 'Vehicle document', 'verbose_name_plural': 'Vehicle documents'},
        ),
        migrations.AlterModelOptions(
            name='violation',
            options={'verbose_name': 'Violation', 'verbose_name_plural': 'Violations'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Failed login'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('CHANGE_STATUS', 'Status change'), ('PICKUP', 'Pickup'), ('RETURN', 'Return')], max_length=20, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='change_summary',
            field=models.CharField(blank=True, max_length=500, verbose_name='Change summary'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Content type'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(null=True, verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Object ID'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_repr',
            field=models.CharField(blank=True, max_length=200, verbose_name='Object representation'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, verbose_name='Session key'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500, verbose_name='User agent'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='username',
            field=models.CharField(blank=True, max_length=150, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='actual_return',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual return'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='fleet.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(max_length=200, verbose_name='Customer name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(max_length=20, verbose_name='Customer phone'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Deposit'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='fleet.driver', verbose_name='Driver'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='expected_return',
            field=models.DateTimeField(verbose_name='Expected return'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_date',
            field=models.DateTimeField(verbose_name='Pickup date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_km',
            field=models.IntegerField(default=0, verbose_name='Pickup km'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='return_km',
            field=models.IntegerField(blank=True, null=True, verbose_name='Return km'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('rented', 'Rented'), ('returned', 'Returned'), ('late', 'Late'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='fleet.vehicle', verbose_name='Vehicle'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='cin',
            field=models.CharField(max_length=20, unique=True, verbose_name='CIN number'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='fleet.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_expiry',
            field=models.DateField(verbose_name='License expiry'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=30, verbose_name='License number'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='fleet.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='km_at_service',
            field=models.IntegerField(verbose_name='Km at service'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='next_service_date',
            field=models.DateField(blank=True, null=True, verbose_name='Next service (date)'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='next_service_km',
            field=models.IntegerField(blank=True, null=True, verbose_name='Next service at (km)'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='fleet.vehicle', verbose_name='Vehicle'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='fleet.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='fleet.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='current_km',
            field=models.IntegerField(default=0, verbose_name='Current km'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Daily rate'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=20, unique=True, verbose_name='License plate'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(max_length=50, verbose_name='Make'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('maintenance', 'Maintenance'), ('out_of_service', 'Out of service')], default='available', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='vehicledocument',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='fleet.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='vehicledocument',
            name='doc_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Document number'),
        ),
        migrations.AlterField(
            model_name='vehicledocument',
            name='doc_type',
            field=models.CharField(choices=[('carte_grise', 'Registration card'), ('insurance', 'Insurance'), ('visite_technique', 'Technical inspection'), ('vignette', 'Vignette')], max_length=30, verbose_name='Document type'),
        ),
        migrations.AlterField(
            model_name='vehicledocument',
            name='expiry_date',
            field=models.DateField(verbose_name='Expiry date'),
        ),
        migrations.AlterField(
            model_name='vehicledocument',
            name='file',
            field=models.FileField(blank=True, upload_to=fleet.validators.DocumentUploadTo(), validators=[fleet.validators.validate_file_extension, fleet.validators.validate_file_size, fleet.validators.validate_mime_type], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='vehicledocument',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fleet.vehicle', verbose_name='Vehicle'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='fleet.booking', verbose_name='Booking'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='fleet.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='fleet.driver', verbose_name='Driver'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fine amount'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='majoration_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Surcharge'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='notification_date',
            field=models.DateField(blank=True, null=True, verbose_name='Notification date'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='paid_by',
            field=models.CharField(blank=True, max_length=20, verbose_name='Paid by'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='payment_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Payment deadline'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='points_deducted',
            field=models.IntegerField(default=0, verbose_name='Points deducted'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='pv_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='PV number'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('driver_designated', 'Driver designated'), ('paid', 'Paid'), ('disputed', 'Disputed'), ('overdue', 'Overdue')], default='new', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='violations', to='fleet.vehicle', verbose_name='Vehicle'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='violation_date',
            field=models.DateTimeField(verbose_name='Violation date'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='violation_location',
            field=models.CharField(blank=True, max_length=300, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='violation_type',
            field=models.CharField(choices=[('speeding', 'Speeding'), ('red_light', 'Red light'), ('seatbelt', 'Seatbelt'), ('phone', 'Phone use'), ('parking', 'Parking'), ('other', 'Other')], default='other', max_length=30, verbose_name='Violation type'),
        ),
    ]
