# Generated by Django 6.0.7 on 2026-07-31 20:31

import django.db.models.deletion
from django.db import migrations, models


def backfill_auditlog_company(apps, schema_editor):
    AuditLog = apps.get_model('fleet', 'AuditLog')
    VehicleDocument = apps.get_model('fleet', 'VehicleDocument')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ct = ContentType.objects.filter(app_label='fleet', model='vehicledocument').first()
    if ct is None:
        return
    for log in AuditLog.objects.filter(content_type=ct).only('id', 'object_id', 'company_id').iterator():
        doc = (
            VehicleDocument.objects.filter(pk=log.object_id)
            .select_related('vehicle')
            .only('id', 'vehicle__company_id')
            .first()
        )
        if doc is not None and doc.vehicle_id:
            log.company_id = doc.vehicle.company_id
            log.save(update_fields=['company_id'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_alter_auditlog_options_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='fleet.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='download_token_version',
            field=models.PositiveIntegerField(default=1, verbose_name='Download token version'),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Original filename'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Failed login'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('CHANGE_STATUS', 'Status change'), ('PICKUP', 'Pickup'), ('RETURN', 'Return'), ('DOWNLOAD', 'Download')], max_length=20, verbose_name='Action'),
        ),
        migrations.RunPython(backfill_auditlog_company, noop),
    ]
