# Generated by Django 6.0.8 on 2026-08-24 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_auditlog_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Audit log', 'verbose_name_plural': 'Audit logs'},
        ),
    ]
